variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true"

image: maven:3.6.3-jdk-11

cache:
  paths:
    - .m2/repository

stages:
  - compile
  - test
  - publish

compilation:
  stage: compile
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests

unit-tests:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS clean verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

artifact-publish:
  stage: publish
  script:
    - mvn $MAVEN_CLI_OPTS clean install -DskipTests
  only:
    refs:
      - master
  artifacts:
    paths: [ "target/*.jar" ]
    expire_in: 3 days